on: 
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          last_tags=($(git tag | tail -n 2))
          changed_files=($(git diff ${last_tags[0]} ${last_tags[1]}))
          for f in $changed_files; do echo $f; done
